### PR TITLE
Update images in local docker compose stack

### PR DESCRIPTION
**Pull request by lukas-phaf**
Update postgres image to latest in postgres 13.

Update nginx base image. I don't see why it used a Python image.

### CODE REVIEW

**Comment by lukas-phaf** [comment]
I see the following errors in the nginx log:
```
nginx-adaguc      | 2023/08/23 12:48:11 [warn] 16#16: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:34
nginx-adaguc      | nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:34
nginx-adaguc      | ls: /etc/letsencrypt/live: No such file or directory
nginx-adaguc      | + certbot certonly --webroot -w /acme -n --agree-tos --email adaguc@knmi.nl -d http://localhost --expand
nginx-adaguc      | Requested name http://localhost appears to be a URL, not a FQDN. Try again without the leading "http://".
nginx-adaguc      | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-ugpytzry/log or re-run Certbot with -v for more details.
nginx-adaguc      | WARNING: Certbot failed to create certificate
```
Exactly the same errors also show up when starting the old nginx container.

**Comment by lukas-phaf** [comment]
I see the following new errors in the postgres container when starting up:
```
adaguc-db  | 2023-08-23 13:27:27.845 UTC [72] ERROR:  relation "autoconfigure_dimensions" does not exist at character 15
adaguc-db  | 2023-08-23 13:27:27.845 UTC [72] STATEMENT:  SELECT * FROM autoconfigure_dimensions where layerid=E't20230823t132727845_sp9vafl8pe1ubamziivl_baselayer'
adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] ERROR:  unterminated quoted string at or near "E't20230823t132727845_sp9vafl8pe1ubamziivl" at character 57
adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] STATEMENT:  delete FROM autoconfigure_dimensions where layerid like E't20230823t132727845_sp9vafl8pe1ubamziivl
adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] ERROR:  unterminated quoted string at or near "E't20230823t132727848_uyn9yguoyunoi44mqy4b" at character 57
adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] STATEMENT:  delete FROM autoconfigure_dimensions where layerid like E't20230823t132727848_uyn9yguoyunoi44mqy4b
```

**Comment by maartenplieger** [comment]
> I see the following errors in the nginx log:
> 
> ```
> nginx-adaguc      | 2023/08/23 12:48:11 [warn] 16#16: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:34
> nginx-adaguc      | nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:34
> nginx-adaguc      | ls: /etc/letsencrypt/live: No such file or directory
> nginx-adaguc      | + certbot certonly --webroot -w /acme -n --agree-tos --email adaguc@knmi.nl -d http://localhost --expand
> nginx-adaguc      | Requested name http://localhost appears to be a URL, not a FQDN. Try again without the leading "http://".
> nginx-adaguc      | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-ugpytzry/log or re-run Certbot with -v for more details.
> nginx-adaguc      | WARNING: Certbot failed to create certificate
> ```
> 
> Exactly the same errors also show up when starting the old nginx container.

This is not a real issue for this update. Added a task to the board to fix in the future.

**Comment by maartenplieger** [comment]
> I see the following new errors in the postgres container when starting up:
> 
> ```
> adaguc-db  | 2023-08-23 13:27:27.845 UTC [72] ERROR:  relation "autoconfigure_dimensions" does not exist at character 15
> adaguc-db  | 2023-08-23 13:27:27.845 UTC [72] STATEMENT:  SELECT * FROM autoconfigure_dimensions where layerid=E't20230823t132727845_sp9vafl8pe1ubamziivl_baselayer'
> adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] ERROR:  unterminated quoted string at or near "E't20230823t132727845_sp9vafl8pe1ubamziivl" at character 57
> adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] STATEMENT:  delete FROM autoconfigure_dimensions where layerid like E't20230823t132727845_sp9vafl8pe1ubamziivl
> adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] ERROR:  unterminated quoted string at or near "E't20230823t132727848_uyn9yguoyunoi44mqy4b" at character 57
> adaguc-db  | 2023-08-23 13:27:27.853 UTC [72] STATEMENT:  delete FROM autoconfigure_dimensions where layerid like E't20230823t132727848_uyn9yguoyunoi44mqy4b
> ```

I checked, but I cannot reproduce these errors after doing compose down and then docker compose up

**Review by maartenplieger — APPROVED** [review]

**Pull request merged**
